language: php

branches:
  only:
    - master

php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  global:
    - TARGET=ci

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install: composer self-update

before_install:
  - composer self-update
  - if [ -x .travis/before_install_${TARGET}.sh ]; then .travis/before_install_${TARGET}.sh; fi;

install:
  - if [ -x .travis/install_${TARGET}.sh ]; then .travis/install_${TARGET}.sh; fi;

script:
  - make $TARGET

after_success:
  - if [ -x .travis/after_success_${TARGET}.sh ]; then .travis/after_success_${TARGET}.sh; fi;

